# define a local repository to the 'distrib' directory above us
# new_local_repository(
#     name = "halide-root",
#     #path = "/usr/local/google/home/srj/Projects/Halide",
#     path = "/Users/srj/Projects/Halide",
#     build_file = "halide-root.BUILD",
# )

# new_local_repository(
#     name = "halide-distrib",
#     #path = "/usr/local/google/home/srj/Projects/Halide",
#     path = "/Users/srj/distrib",  # _trunk_clang_fe99d863aeff6ac9a128d65b976cfe0caff50b77_2015_06_03
#     build_file = "halide-distrib.BUILD",
# )

# new_http_archive(
#     name = "halide-distrib-win32",
#     url = "https://github.com/halide/Halide/releases/download/release_2015_06_03/Halide_Windows_32_trunk_fe99d863aeff6ac9a128d65b976cfe0caff50b77_2015_06_03.zip",
#     sha256 = "5575457c56a29e5f1b18dd8695bde80989214b8d2b3390895052959ad91dbdde",
#     build_file = "halide-distrib-win32.BUILD",
# )

new_git_repository(
    name="zlib-github",
    build_file="zlib.BUILD",
    remote="https://github.com/madler/zlib",
    tag='v1.2.8'
)

new_git_repository(
    name="libpng-github",
    build_file="libpng.BUILD",
    remote="https://github.com/glennrp/libpng",
    tag="v1.6.18-master"
)

new_http_archive(
    name = "halide-distrib-darwin-64",
    url = "https://github.com/halide/Halide/releases/download/release_2015_06_03/halide_Darwin_64_trunk_clang_fe99d863aeff6ac9a128d65b976cfe0caff50b77_2015_06_03.tgz",
    sha256 = "d2f866a4c4a3562416c5e1d3b86363e624042a4f758185f0d9b1c2754b251092",
    build_file = "halide-distrib-darwin-64.BUILD",
)

bind(
    name='halide_runtime',
    actual='@halide-distrib-darwin-64//:halide_runtime'
)

bind(
    name='lib_halide',
    actual='@halide-distrib-darwin-64//:lib_halide'
)

bind(
    name='zlib',
    actual='@zlib-github//:zlib'
)

bind(
    name='libpng',
    actual='@libpng-github//:libpng'
)
